# Generated by Django 4.2.2 on 2023-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address_1', models.CharField(max_length=150, null=True)),
                ('user_address_2', models.CharField(max_length=150, null=True)),
                ('user_pincode', models.CharField(max_length=6, null=True)),
                ('user_email', models.CharField(max_length=100, null=True)),
                ('user_phone', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
