# Generated by Django 4.2.2 on 2023-08-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
