# Generated by Django 4.2.2 on 2023-08-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
