# Generated by Django 4.2.2 on 2023-08-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='var',
            new_name='user',
        ),
    ]
