# Generated by Django 4.2.2 on 2023-08-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='var',
        ),
    ]
