# Generated by Django 4.2.2 on 2023-08-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
    ]
