# Generated by Django 4.2.2 on 2023-08-26 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('app', '0040_alter_bill_id_alter_order_id'), ('app', '0041_alter_bill_id_alter_order_id')]

    dependencies = [
        ('app', '0039_alter_bill_id_alter_order_id_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
