# Generated by Django 4.2.2 on 2023-08-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='item',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.products'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
