# Generated by Django 4.2.2 on 2023-08-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_bill_item_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='item',
        ),
    ]
