# Generated by Django 4.2.2 on 2023-08-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
